pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
    }

    options {
        timestamps()
        timeout(time: 1, unit: 'HOURS')
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    triggers {
        pollSCM('H/2 * * * *') // Poll every 2 minutes
    }

    environment {
        APP_NAME = 'taskify-backend'
        DOCKER_REGISTRY = 'docker.io'
        DOCKER_IMAGE_NAME = "${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${APP_NAME}"
        SONAR_PROJECT_KEY = 'taskify-backend'
        SLACK_CHANNEL = '#builds'

        SPRING_APPLICATION_NAME = 'taskify-backend'
        SERVER_PORT = '8080'

        SPRING_DATASOURCE_URL = 'jdbc:h2:mem:testdb'
        SPRING_DATASOURCE_USERNAME = 'sa'
        SPRING_DATASOURCE_PASSWORD = ''

        JWT_SECRET = credentials('JWT_SECRET')
        JWT_EXPIRATION = '86400000'

        TEST_JWT_SECRET = credentials('TEST_JWT_SECRET')
        TEST_JWT_EXPIRATION = '3600000'
        TEST_USER_EMAIL = 'test@example.com'
        TEST_USER_PASSWORD = 'password123'
        TEST_USER_NEW_EMAIL = 'newuser@example.com'
        TEST_USER_EXISTING_EMAIL = 'existing@example.com'
    }

    stages {
        stage('Detect OS') {
            steps {
                script {
                    env.IS_UNIX = isUnix() ? 'true' : 'false'
                    echo "Detected ${env.IS_UNIX == 'true' ? 'Unix/Linux' : 'Windows'} environment"
                }
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
                script {
                    echo "Creating .env file..."
                    if (env.IS_UNIX == 'true') {
                        sh """
                        echo SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME} > .env
                        echo SERVER_PORT=${SERVER_PORT} >> .env
                        echo SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL} >> .env
                        echo SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME} >> .env
                        echo SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD} >> .env
                        echo JWT_SECRET=${JWT_SECRET} >> .env
                        echo JWT_EXPIRATION=${JWT_EXPIRATION} >> .env
                        echo TEST_JWT_SECRET=${TEST_JWT_SECRET} >> .env
                        echo TEST_JWT_EXPIRATION=${TEST_JWT_EXPIRATION} >> .env
                        echo TEST_USER_EMAIL=${TEST_USER_EMAIL} >> .env
                        echo TEST_USER_PASSWORD=${TEST_USER_PASSWORD} >> .env
                        echo TEST_USER_NEW_EMAIL=${TEST_USER_NEW_EMAIL} >> .env
                        echo TEST_USER_EXISTING_EMAIL=${TEST_USER_EXISTING_EMAIL} >> .env
                        """
                    } else {
                        bat """
                        @echo off
                        echo SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}> .env
                        echo SERVER_PORT=${SERVER_PORT}>> .env
                        echo SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}>> .env
                        echo SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}>> .env
                        echo SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}>> .env
                        echo JWT_SECRET=${JWT_SECRET}>> .env
                        echo JWT_EXPIRATION=${JWT_EXPIRATION}>> .env
                        echo TEST_JWT_SECRET=${TEST_JWT_SECRET}>> .env
                        echo TEST_JWT_EXPIRATION=${TEST_JWT_EXPIRATION}>> .env
                        echo TEST_USER_EMAIL=${TEST_USER_EMAIL}>> .env
                        echo TEST_USER_PASSWORD=${TEST_USER_PASSWORD}>> .env
                        echo TEST_USER_NEW_EMAIL=${TEST_USER_NEW_EMAIL}>> .env
                        echo TEST_USER_EXISTING_EMAIL=${TEST_USER_EXISTING_EMAIL}>> .env
                        """
                    }
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    runCommand('mvn clean compile')
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    runCommand('mvn test')
                }
            }
            post {
                always {
                    junit testResults: 'target/surefire-reports/**/*.xml', allowEmptyResults: true
                }
            }
        }

        stage('Code Coverage & Analysis') {
            steps {
                script {
                    runCommand('mvn jacoco:report')
                }
            }
        }

        stage('SonarQube Analysis') {
            when {
                branch 'master'
            }
            steps {
                script {
                    echo "SonarQube analysis stage - configure your SonarQube here"
                }
            }
        }

        stage('Package') {
            steps {
                script {
                    runCommand('mvn package -DskipTests')
                }
            }
            post {
                success {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }

        stage('Docker Preflight') {
            steps {
                script {
                    env.DOCKER_AVAILABLE = 'false'
                    if (env.IS_UNIX == 'true') {
                        def hasDocker = (sh(script: 'command -v docker >/dev/null 2>&1', returnStatus: true) == 0)
                        def hasSock = fileExists('/var/run/docker.sock')
                        if (hasDocker && hasSock) env.DOCKER_AVAILABLE = 'true'
                    } else {
                        def hasDocker = (bat(script: 'docker --version', returnStatus: true) == 0)
                        if (hasDocker) env.DOCKER_AVAILABLE = 'true'
                    }
                    echo "Docker available: ${env.DOCKER_AVAILABLE}"
                }
            }
        }

        stage('Build Docker Image') {
            when {
                environment name: 'DOCKER_AVAILABLE', value: 'true'
            }
            steps {
                script {
                    runCommand("docker build -t ${APP_NAME}:${BUILD_NUMBER} .")
                    runCommand("docker tag ${APP_NAME}:${BUILD_NUMBER} ${APP_NAME}:latest")
                }
            }
        }

        stage('Push to Registry') {
            when {
                allOf {
                    environment name: 'DOCKER_AVAILABLE', value: 'true'
                    branch 'master'
                }
            }
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        if (env.IS_UNIX == 'true') {
                            sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                        } else {
                            bat 'docker login -u %DOCKER_USER% -p %DOCKER_PASS%'
                        }
                        runCommand("docker tag ${APP_NAME}:${BUILD_NUMBER} ${DOCKER_USER}/${APP_NAME}:${BUILD_NUMBER}")
                        runCommand("docker push ${DOCKER_USER}/${APP_NAME}:${BUILD_NUMBER}")
                    }
                }
            }
        }
    }

    post {
        always { cleanWs() }
        success { echo "Pipeline SUCCESS" }
        failure { echo "Pipeline FAILURE" }
    }
}

// Helper function inside a script block
def runCommand(String command) {
    if (isUnix()) {
        sh command
    } else {
        bat command
    }
}
